#Файл конфигурации EvilRumor
#Конфигурация ревизии 1.0
#Для установки игроков в сообщения используйте
#%player1% - для погибшего игрока
#%player2% - для убийцы
#Учтите, что плагин не отображает действительные смерти, а возвращает рандомных игроков,
#тем самым специально их посдтавляя
messages:
  [
  "Говорят %player1% убил игрока %player2%.",
  "Вы вроде бы услышали крики %player1%, но это не точно...",
  "Пошли слухи, что %player1% трагически погиб!"
  ]